In [3]:
lst = [1,2,3,4,5,6,7,8,9,10]

### numpy

In [4]:
arr = np.array(lst)

<IPython.core.display.Javascript object>

In [7]:
%timeit arr**2

612 ns ± 13.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [6]:
arr+1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### numpy basics


In [8]:
l=[1,5,8,9]
np_arr=np.array(l)


<IPython.core.display.Javascript object>

In [9]:
np_arr


array([1, 5, 8, 9])

In [10]:
type(np_arr)

numpy.ndarray

In [11]:
np_arr.ndim

1

In [12]:
np_arr.shape

(4,)

In [13]:
new_arr=np.arange(3,11)

<IPython.core.display.Javascript object>

In [14]:
new_arr

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
lst_2d=[[1,2,3],[4,5,6],[7,8,9]]

In [17]:
arr_2d=np.array(lst_2d)

<IPython.core.display.Javascript object>

In [18]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr_2d.shape

(3, 3)

In [20]:
arr_2d.ndim

2

### special array

In [23]:
np.zeros(2)

<IPython.core.display.Javascript object>

array([0., 0.])

In [26]:
np.zeros((2,2))

<IPython.core.display.Javascript object>

array([[0., 0.],
       [0., 0.]])

In [27]:
np.ones((5,5))

<IPython.core.display.Javascript object>

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
np.diag([1,13,4,5])

<IPython.core.display.Javascript object>

array([[ 1,  0,  0,  0],
       [ 0, 13,  0,  0],
       [ 0,  0,  4,  0],
       [ 0,  0,  0,  5]])

In [29]:
np.identity(4)

<IPython.core.display.Javascript object>

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### indexing in array

In [30]:
np.random.randint(10,100)

<IPython.core.display.Javascript object>

19

In [31]:
new_arr=np.random.randint(0,20,(5,4))

<IPython.core.display.Javascript object>

In [32]:
new_arr

array([[18,  5,  4, 12],
       [ 6,  2, 12,  4],
       [ 9,  2,  8,  9],
       [10, 15, 12,  7],
       [15,  2,  3, 16]])

In [33]:
new_arr.shape


(5, 4)

In [34]:
new_arr[0]

array([18,  5,  4, 12])

In [35]:
new_arr[-2]

array([10, 15, 12,  7])

In [37]:
new_arr[0]

array([18,  5,  4, 12])

In [39]:
new_arr[0,0]

18

In [40]:
new_arr[4,3]

16

### array slicing


In [41]:
new_arr

array([[18,  5,  4, 12],
       [ 6,  2, 12,  4],
       [ 9,  2,  8,  9],
       [10, 15, 12,  7],
       [15,  2,  3, 16]])

In [42]:
new_arr[2:,1:]

array([[ 2,  8,  9],
       [15, 12,  7],
       [ 2,  3, 16]])

In [43]:
new_arr[:,-1]

array([12,  4,  9,  7, 16])

### BASIC OPERATIONS

In [44]:
a=np.array([10,20,30,40])
b=np.arange(1,5)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [45]:
a


array([10, 20, 30, 40])

In [46]:
b

array([1, 2, 3, 4])

In [47]:
a+b

array([11, 22, 33, 44])

In [48]:
a-b

array([ 9, 18, 27, 36])

In [49]:
a*b

array([ 10,  40,  90, 160])

In [50]:
a**2

array([ 100,  400,  900, 1600], dtype=int32)

In [51]:
np.log(b)

<IPython.core.display.Javascript object>

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [53]:
np.sin(b)

<IPython.core.display.Javascript object>

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [54]:
p1 = np.array([1,2, 4, 7, -2, 9, 6, 0])
p2 = np.array([5,5, 8, 2, -9, 2, 1, 6])

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [56]:
p1.shape

(8,)